{# use '2.1' cause it's the version in freebsd ports tree #}
{% set major_version = '2.1' %}

{% load_yaml as lookup %}
Debian:
    repo_url: "deb http://packages.elastic.co/logstash/{{major_version}}/debian stable main"
    repo_file: /etc/apt/sources.list.d/logstash.list
    gpg_url: "https://packages.elasticsearch.org/GPG-KEY-elasticsearch"
    package: logstash
    service: logstash
    config_file: /etc/logstash/logstash.conf.example
CentOS:
    repo_url: "http://packages.elastic.co/logstash/{{major_version}}/centos"
    repo_file: /etc/yum.repos.d/logstash.repo
    gpg_url: "https://packages.elasticsearch.org/GPG-KEY-elasticsearch"
    package: logstash
    service: logstash
    config_file: /etc/logstash/logstash.conf.example
FreeBSD:
    package: logstash
    service: logstash
    config_file: /usr/local/etc/logstash/logstash.conf.example
{% endload %}

{% load_yaml as rawmap %}
{% endload %}
